    DECLARE @v_cnt FLOAT;
BEGIN
    SELECT @v_cnt = COUNT(*)
    FROM sys.sysusers
    WHERE NAME = 'C##TMPUSER';

    IF @v_cnt > 0 BEGIN
        EXECUTE sp_executesql 'DROP USER C##TMPUSER CASCADE';
    END 
END;
/
CREATE USER C##TMPUSER WITH Password=N'CorrectHorseBatteryStaple'
/
USE master
GRANT CONNECT ANY DATABASE TO C##TMPUSER
/
GRANT CREATE TABLE TO C##TMPUSER
/
GRANT CREATE VIEW TO C##TMPUSER
/
GRANT VIEW ANY DEFINITION TO C##TMPUSER
/
GRANT ALTER ANY DATABASE DDL TRIGGER TO C##TMPUSER
/
GRANT CREATE PROCEDURE TO C##TMPUSER
/ 
GRANT ALTER ANY SCHEMA TO C##TMPUSER
/
GRANT CREATE SYNONYM TO C##TMPUSER
/