USE evolutionDB;
GO
DROP FUNCTION IF EXISTS FUNC_GET_APP_DESCRIPTION;
GO
CREATE FUNCTION FUNC_GET_APP_DESCRIPTION (@I_APP_ID FLOAT)
	RETURNS VARCHAR(4000)
AS

BEGIN
    DECLARE @V_APP_DESCRIPTION VARCHAR(4000);
 
	SELECT @V_APP_DESCRIPTION = A.APP_DESCRIPTION
	FROM APP_TABLE A
	WHERE A.APP_ID = @I_APP_ID;

    RETURN @V_APP_DESCRIPTION;
END 
GO