IF OBJECT_ID('C##TMPUSER.FUNC_GET_APP_DESCRIPTION', 'FN') IS NOT NULL
  DROP FUNCTION C##TMPUSER.FUNC_GET_APP_DESCRIPTION;
GO

CREATE FUNCTION C##TMPUSER.FUNC_GET_APP_DESCRIPTION (@I_APP_ID FLOAT)
	RETURNS VARCHAR(4000)
AS

BEGIN
  DECLARE @V_APP_DESCRIPTION VARCHAR(4000) /* Use -meta option C##TMPUSER.APP_TABLE.APP_DESCRIPTION%TYPE */;
 
	BEGIN
	   SELECT @V_APP_DESCRIPTION = A.APP_DESCRIPTION
	   FROM C##TMPUSER.APP_TABLE A
	   WHERE A.APP_ID = @I_APP_ID;

	END;

    RETURN @V_APP_DESCRIPTION;
END 
GO

FUNC_GET_APP_DESCRIPTION;