CREATE OR ALTER TRIGGER C##TMPUSER.TRIG_BI_APP_TABLE	
ON C##TMPUSER.APP_TABLE
INSTEAD OF INSERT AS

BEGIN
 
	DECLARE @NEW_CREATED_DATE	DATE
	DECLARE @NEW_CREATED_BY	VARCHAR(100)

	SELECT @NEW_CREATED_DATE	= SYSDATE;
	SELECT @NEW_CREATED_BY	= USER;

	INSERT INTO C##TMPUSER.APP_TABLE (APP_ID, APP_DESCRIPTION, CREATED_DATE, CREATED_BY) SELECT insterted.APP_ID, inserted.APP_DESCRIPTION, @NEW_CREATED_DATE, @NEW_CREATED_BY FROM inserted
END