CREATE USER C##TMP_USER IDENTIFIED BY CorrectHorseBatteryStaple
/
GRANT CREATE SESSION TO C##TMP_USER
/
GRANT CREATE TABLE TO C##TMP_USER
/
GRANT CREATE VIEW TO C##TMP_USER
/
GRANT CREATE ANY TRIGGER TO C##TMP_USER
/
GRANT CREATE ANY PROCEDURE TO C##TMP_USER
/
GRANT CREATE SEQUENCE TO C##TMP_USER
/
GRANT CREATE SYNONYM TO C##TMP_USER
/
ALTER USER C##TMP_USER QUOTA UNLIMITED ON SYSTEM
/