CREATE USER C##TMPUSER IDENTIFIED BY CorrectHorseBatteryStaple
/
GRANT CREATE SESSION TO C##TMPUSER
/
GRANT CREATE TABLE TO C##TMPUSER
/
GRANT CREATE VIEW TO C##TMPUSER
/
GRANT CREATE ANY TRIGGER TO C##TMPUSER
/
GRANT CREATE ANY PROCEDURE TO C##TMPUSER
/
GRANT CREATE SEQUENCE TO C##TMPUSER
/
GRANT CREATE SYNONYM TO C##TMPUSER
/
ALTER USER C##TMPUSER QUOTA UNLIMITED ON SYSTEM
/