CREATE USER TMP_USER IDENTIFIED BY CorrectHorseBatteryStaple;
GRANT CREATE SESSION TO TMP_USER;
GRANT CREATE TABLE TO TMP_USER;
GRANT CREATE VIEW TO TMP_USER
GRANT create view TO TMP_USER;
GRANT create any trigger TO TMP_USER;
GRANT create any procedure TO TMP_USER;
GRANT create sequence TO TMP_USER;
GRANT create synonym TO TMP_USER;