CREATE OR REPLACE FUNCTION TMP_USER.FUNC_GET_APP_DESCRIPTION (I_APP_ID IN NUMBER)
	RETURN VARCHAR2
IS
  V_APP_DESCRIPTION TMP_USER.APP_TABLE.APP_DESCRIPTION%TYPE;
BEGIN
   BEGIN
	   SELECT A.APP_DESCRIPTION
	   INTO V_APP_DESCRIPTION
	   FROM TMP_USER.APP_TABLE A
	   WHERE A.APP_ID = I_APP_ID;

	EXCEPTION
	  WHEN OTHERS THEN
		V_APP_DESCRIPTION := '';
	END;

    RETURN V_APP_DESCRIPTION;
END GET_APP_DESCRIPTION;