DROP TABLE IF EXISTS APP_TABLE
GO
CREATE TABLE [APP_TABLE](
	[APP_ID]				INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	[APP_DESCRIPTION]		VARCHAR(100),
	[CREATED_DATE]		    DATETIME,
	[CREATED_BY]			VARCHAR(30)
)
GO