DROP TRIGGER IF EXISTS TRIG_BI_APP_TABLE;
GO
CREATE TRIGGER TRIG_BI_APP_TABLE	
ON APP_TABLE
INSTEAD OF INSERT AS

BEGIN
	INSERT INTO APP_TABLE (APP_DESCRIPTION, CREATED_DATE, CREATED_BY) 
		SELECT inserted.APP_DESCRIPTION, 
			   GETDATE(), 
			   USER 
		FROM inserted;
END